<?php

namespace tests\unit\models;

use app\commons\SecurityUtil;
use app\models\AppInfo;
use app\models\ComponentInfo;
use Codeception\Test\Unit;
use Curl\Curl;

class AppInfoTest extends Unit
{
    private static $appId;

    protected function setUp()
    {
        return parent::setUp();
    }

    protected function tearDown()
    {
        AppInfo::deleteAll();
        parent::tearDown();
    }

    public static function setUpBeforeClass()
    {
        parent::setUpBeforeClass(); // TODO: Change the autogenerated stub
        self::$appId = 'wx4d7309ab40402897';
    }

    public static function tearDownAfterClass()
    {
        parent::tearDownAfterClass(); // TODO: Change the autogenerated stub
    }

    /**
     * appinfo表插入操作
     * @throws \Exception
     */
    public function testInsert()
    {
        $appInfo = new AppInfo();
        $appInfo->appId = self::$appId;
        $appInfo->accessToken = 'AoDW5N1BeAInQD8p_XvqfioSAzSdgfWkKVhlOBQmZfy_RI4rDp9UgyVBrvdt1YpFeL8A0Kyw3PhLxfImKcQlt1TsQXAOW3RCVMCU-8OMvc8v2ih56A4QYLt3-NtDIArSWVBfAKDNMS';
        $appInfo->refreshToken = 'refreshtoken@@@Fhbmc3IRVXLQEkN8xHRCc9tMKn2m1QpbtVfFR9YXRGw';
        $appInfo->funcScopeCategory = '[1,15,4,7,2,3,11,6]';
        $appInfo->expiresIn = 7200;
        $appInfo->zeroUpdatedAt = 1478066543;
        $appInfo->nickName = '圣雄阿v';
        $appInfo->headImg = 'http://wx.qlogo.cn/mmopen/IH40gWTSAGGNnqmDIJReZynUgsdQQRU0CNxEfbthzQicD9o6ib2tolVMK20UnMxs1ZYYULMW9GcibxmGebOLuibsZakVLzpcp2xib/0';
        $appInfo->serviceTypeInfo = 1;
        $appInfo->verifyTypeInfo = -1;
        $appInfo->userName = 'gh_3b3df480927d';
        $appInfo->alias = null;
        $appInfo->businessInfoOpenCard = 0;
        $appInfo->businessInfoOpenPay = 0;
        $appInfo->businessInfoOpenScan = 0;
        $appInfo->businessInfoOpenShake = 0;
        $appInfo->businessInfoOpenStore = 0;
        $appInfo->qrcodeUrl = 'http://mmbiz.qpic.cn/mmbiz_jpg/Eq4icPfUwRBHspkuQPBZCuia6JTic9W6fwnecyicBu27uhgHlcUNpUlFJt7nOaUbcFOsM0gCUowsJCjsUq16lGGN5A/0';
        $appInfo->oneUpdatedAt = 1478067699;
        $appInfo->componentAppId = 'wx836d8c653bd41442';
        $appInfo->infoType = 'unauthorized';
        $appInfo->authorizationCode = '';
        $appInfo->authorizationCodeExpiredTime = 1478071297;
        $appInfo->twoUpdatedAt = 1478067769;

        $this->assertEquals(true, $appInfo->insert(), 'appInfo insert db failed!');
    }

    /**
     * appInfo表更新操作
     */
    public function testUpdate()
    {
        $this->appInfoInsert(self::$appId);
        $flag = AppInfo::updateAll(
            [
                'authorizationCode' => '',
                'authorizationCodeExpiredTime' => time(),
                'twoUpdatedAt' => time(),
                'infoType' => 'authorized',
                'qrcodeUrl' => 'http://mmbiz.qpic.cn/mmbiz_jpg/Eq4icPfUwRBHspkuQPBZCuia6JTic9W6fwnecyicBu27uhgHlcUNp',
                'nickName' => 'sdf',
                'serviceTypeInfo' => 2,
                'verifyTypeInfo' => 1,
                'funcScopeCategory' => '[1,15,4,7,2,3,11]',
                'accessToken' => 'AoDW5N1BeAInQD8p_XvqfioSAzSdgfWkKVhlOBQmZfy_RI4rDp9UgyV',
                'refreshToken' => 'refreshtoken@@@Fhbmc3IRVXLQEkN8xHRCc9tMKn2m1Qp',
                'expiresIn' => 3020,
                'zeroUpdatedAt' => 1478068543
            ],
            ['appId' => self::$appId]
        );
        $this->assertEquals(1, $flag, 'appInfo update db failed!');
    }

    /**
     * 缺少appid 插入异常
     * @expectedException yii\db\IntegrityException
     */
    public function testInsertLackAppid()
    {
        $appInfo = new AppInfo();
        $appInfo->appId = null;
        $appInfo->accessToken = 'AoDW5N1BeAInQD8p_XvqfioSAzSdgfWkKVhlOBQmZfy_RI4rDp9UgyVBrvdt1YpFeL8A0Kyw3PhLxfImKcQlt1TsQXAOW3RCVMCU-8OMvc8v2ih56A4QYLt3-NtDIArSWVBfAKDNMS';
        $appInfo->refreshToken = 'refreshtoken@@@Fhbmc3IRVXLQEkN8xHRCc9tMKn2m1QpbtVfFR9YXRGw';
        $appInfo->funcScopeCategory = '[1,15,4,7,2,3,11,6]';
        $appInfo->expiresIn = 7200;
        $appInfo->zeroUpdatedAt = 1478066543;
        $appInfo->nickName = '圣雄阿v';
        $appInfo->headImg = 'http://wx.qlogo.cn/mmopen/IH40gWTSAGGNnqmDIJReZynUgsdQQRU0CNxEfbthzQicD9o6ib2tolVMK20UnMxs1ZYYULMW9GcibxmGebOLuibsZakVLzpcp2xib/0';
        $appInfo->serviceTypeInfo = 1;
        $appInfo->verifyTypeInfo = -1;
        $appInfo->userName = 'gh_3b3df480927d';
        $appInfo->alias = null;
        $appInfo->businessInfoOpenCard = 0;
        $appInfo->businessInfoOpenPay = 0;
        $appInfo->businessInfoOpenScan = 0;
        $appInfo->businessInfoOpenShake = 0;
        $appInfo->businessInfoOpenStore = 0;
        $appInfo->qrcodeUrl = 'http://mmbiz.qpic.cn/mmbiz_jpg/Eq4icPfUwRBHspkuQPBZCuia6JTic9W6fwnecyicBu27uhgHlcUNpUlFJt7nOaUbcFOsM0gCUowsJCjsUq16lGGN5A/0';
        $appInfo->oneUpdatedAt = 1478067699;
        $appInfo->componentAppId = 'wx836d8c653bd41442';
        $appInfo->infoType = 'unauthorized';
        $appInfo->authorizationCode = '';
        $appInfo->authorizationCodeExpiredTime = 1478071297;
        $appInfo->twoUpdatedAt = 1478067769;
        $appInfo->insert();

    }

    /**
     * 插入相同appid 异常
     * @expectedException yii\db\IntegrityException
     */
    public function testInsertSameKey()
    {
        $this->appInfoInsert(self::$appId);
        $appInfo = new AppInfo();
        $appInfo->appId = self::$appId;
        $appInfo->accessToken = 'AoDW5N1BeAInQD8p_XvqfioSAzSdgfWkKVhlOBQmZfy_RI4rDp9UgyVBrvdt1YpFeL8A0Kyw3PhLxfImKcQlt1TsQXAOW3RCVMCU-8OMvc8v2ih56A4QYLt3-NtDIArSWVBfAKDNMS';
        $appInfo->refreshToken = 'refreshtoken@@@Fhbmc3IRVXLQEkN8xHRCc9tMKn2m1QpbtVfFR9YXRGw';
        $appInfo->funcScopeCategory = '[1,15,4,7,2,3,11,6]';
        $appInfo->expiresIn = 7200;
        $appInfo->zeroUpdatedAt = 1478066543;
        $appInfo->nickName = '圣雄阿v';
        $appInfo->headImg = 'http://wx.qlogo.cn/mmopen/IH40gWTSAGGNnqmDIJReZynUgsdQQRU0CNxEfbthzQicD9o6ib2tolVMK20UnMxs1ZYYULMW9GcibxmGebOLuibsZakVLzpcp2xib/0';
        $appInfo->serviceTypeInfo = 1;
        $appInfo->verifyTypeInfo = -1;
        $appInfo->userName = 'gh_3b3df480927d';
        $appInfo->alias = null;
        $appInfo->businessInfoOpenCard = 0;
        $appInfo->businessInfoOpenPay = 0;
        $appInfo->businessInfoOpenScan = 0;
        $appInfo->businessInfoOpenShake = 0;
        $appInfo->businessInfoOpenStore = 0;
        $appInfo->qrcodeUrl = 'http://mmbiz.qpic.cn/mmbiz_jpg/Eq4icPfUwRBHspkuQPBZCuia6JTic9W6fwnecyicBu27uhgHlcUNpUlFJt7nOaUbcFOsM0gCUowsJCjsUq16lGGN5A/0';
        $appInfo->oneUpdatedAt = 1478067699;
        $appInfo->componentAppId = 'wx836d8c653bd41442';
        $appInfo->infoType = 'unauthorized';
        $appInfo->authorizationCode = '';
        $appInfo->authorizationCodeExpiredTime = 1478071297;
        $appInfo->twoUpdatedAt = 1478067769;
        $appInfo->insert();
    }

    /**
     *  测试查询 异常
     */
    public function testFindErr()
    {
        $this->appInfoInsert(self::$appId);
        $appId = 'sdfasff';
        $this->assertEmpty(AppInfo::findOne($appId), 'find invalid param error');
        $appId = '';
        $this->assertEmpty(AppInfo::findOne($appId));
        $appId = null;
        $this->assertEmpty(AppInfo::findOne($appId));
        $this->assertEmpty(AppInfo::find()->where(['not in', 'serviceTypeInfo', [1, 2, 0]])->asArray()->all(), 'find invail param error');
        $this->assertEmpty(AppInfo::find()->where(['not in', 'verifyTypeInfo', [-1, 0, 1]])->asArray()->all(), 'find invail param error');
        $this->assertEquals(true, AppInfo::deleteAll(['appId' => self::$appId]), 'delete err');
    }

    /**
     * appinfo 表删除操作
     * @throws \Exception
     */
    public function testDelete()
    {
        $this->appInfoInsert(self::$appId);
        $flag = AppInfo::deleteAll(['appId' => self::$appId]);
        $this->assertEquals(1, $flag, 'appInfo delete db failed!');
    }

    /**
     * 单元测试 从代理平台获取授权token
     */
    public function testGetToken()
    {
        $appId = 'wx57b1371bda498a46';
        $timestamp = time();
        $sign = (new SecurityUtil(['timestamp' => $timestamp, 'appId' => $appId],
            \Yii::$app->params['signKey']['apiSignKey']))->generateSign();
        $url = \Yii::$app->params['serviceDomain']['weiXinApiDomain'] . '/facade/access-token?appId=' . $appId
            . '&timestamp=' . $timestamp . '&sign=' . $sign;
        $curl = new Curl();
        $curl->get($url);

        $respData = json_decode($curl->response, true);
        $this->assertEquals(true, isset($respData['return_code']), 'get token error!');
        $this->assertEquals(true, isset($respData['return_msg']), 'get token error!');
        $this->assertEquals(true, $respData['return_code'] == 'SUCCESS' || $respData['return_code'] == 'FAIL', 'resp error');
        if ($respData['return_code'] == 'SUCCESS') {
            $this->assertEquals(true, isset($respData['return_msg']['accessToken']), 'resp token lack');
        }
    }

    /**
     * 单元测试 从代理平台获取公众号数据
     */
    public function testGetAppInfo()
    {
        $appId = 'wx57b1371bda498a46';
        $timestamp = time();
        $sign = (new SecurityUtil(['timestamp' => $timestamp, 'appId' => $appId],
            \Yii::$app->params['signKey']['apiSignKey']))->generateSign();
        $url = \Yii::$app->params['serviceDomain']['weiXinApiDomain'] . '/facade/app-info?appId=' . $appId
            . '&timestamp=' . $timestamp . '&sign=' . $sign;
        $curl = new Curl();
        $curl->get($url);
        $respData = json_decode($curl->response, true);
        $this->assertEquals(true, isset($respData['return_code']), 'resp return_code lack');
        $this->assertEquals(true, isset($respData['return_msg']), 'resp return_msg lack');
        $this->assertEquals(true, $respData['return_code'] == 'SUCCESS' || $respData['return_code'] == 'FAIL', 'resp_code err');
        if ($respData['return_code'] == 'SUCCESS') {
            $this->assertEquals(true, isset($respData['return_msg']['appId']), 'resp appId lack');
            $this->assertEquals(true, isset($respData['return_msg']['nickName']), 'resp nickName lack');
            $this->assertEquals(true, isset($respData['return_msg']['headImg']), 'resp headImg lack');
            $this->assertEquals(true, isset($respData['return_msg']['serviceType']), 'resp serviceType lack');
            $this->assertEquals(true, isset($respData['return_msg']['verifyType']), 'resp verifyType lack');
            $this->assertEquals(true, isset($respData['return_msg']['alias']), 'resp alias lack');
            $this->assertEquals(true, isset($respData['return_msg']['qrCodeUrl']), 'resp qrCodeUrl lack');
            $this->assertEquals(true, isset($respData['return_msg']['authStatus']), 'resp authStatus lack');
            $this->assertEquals(true, isset($respData['return_msg']['accessToken']), 'resp accessToken lack');
        }
    }

    /**
     * 测试 appinfo 模型
     */
    public function testAppInfo()
    {
        $this->appInfoInsert(self::$appId);
        $this->componentInfoInsert('wx836d8c653bd41442');
        $appInfo = AppInfo::findOne(self::$appId);
        $componentInfo = ComponentInfo::findOne('wx836d8c653bd41442');
        $appInfo->getAuth($componentInfo->accessToken);
        $appInfo->accessToken = null;
        $appInfo->getAuth($componentInfo->accessToken);
        $appInfo->getAuthorizeInfo($componentInfo->accessToken);
        ComponentInfo::deleteAll(['appId' => 'wx836d8c653bd41442']);
    }

    /**
     * appinfo 插入
     * @param $appId
     * @throws \Exception
     */
    public function appInfoInsert($appId)
    {
        $appInfo = new AppInfo();
        $appInfo->appId = $appId;
        $appInfo->accessToken = 'AoDW5N1BeAInQD8p_XvqfioSAzSdgfWkKVhlOBQmZfy_RI4rDp9UgyVBrvdt1YpFeL8A0Kyw3PhLxfImKcQlt1TsQXAOW3RCVMCU-8OMvc8v2ih56A4QYLt3-NtDIArSWVBfAKDNMS';
        $appInfo->refreshToken = 'refreshtoken@@@Fhbmc3IRVXLQEkN8xHRCc9tMKn2m1QpbtVfFR9YXRGw';
        $appInfo->funcScopeCategory = '[1,15,4,7,2,3,11,6]';
        $appInfo->expiresIn = 7200;
        $appInfo->zeroUpdatedAt = 1478066543;
        $appInfo->nickName = '圣雄阿v';
        $appInfo->headImg = 'http://wx.qlogo.cn/mmopen/IH40gWTSAGGNnqmDIJReZynUgsdQQRU0CNxEfbthzQicD9o6ib2tolVMK20UnMxs1ZYYULMW9GcibxmGebOLuibsZakVLzpcp2xib/0';
        $appInfo->serviceTypeInfo = 1;
        $appInfo->verifyTypeInfo = -1;
        $appInfo->userName = 'gh_3b3df480927d';
        $appInfo->alias = null;
        $appInfo->businessInfoOpenCard = 0;
        $appInfo->businessInfoOpenPay = 0;
        $appInfo->businessInfoOpenScan = 0;
        $appInfo->businessInfoOpenShake = 0;
        $appInfo->businessInfoOpenStore = 0;
        $appInfo->qrcodeUrl = 'http://mmbiz.qpic.cn/mmbiz_jpg/Eq4icPfUwRBHspkuQPBZCuia6JTic9W6fwnecyicBu27uhgHlcUNpUlFJt7nOaUbcFOsM0gCUowsJCjsUq16lGGN5A/0';
        $appInfo->oneUpdatedAt = 1478067699;
        $appInfo->componentAppId = 'wx836d8c653bd41442';
        $appInfo->infoType = 'unauthorized';
        $appInfo->authorizationCode = '';
        $appInfo->authorizationCodeExpiredTime = 1478071297;
        $appInfo->twoUpdatedAt = 1478067769;
        $appInfo->insert();
    }

    /**
     * com表插入
     * @param null $appId
     * @throws \Exception
     */
    public function componentInfoInsert($appId = null)
    {
        $componentInfo = new ComponentInfo();
        $componentInfo->appId = $appId ? $appId : self::$appId;
        $componentInfo->infoType = 'component_verify_ticket';
        $componentInfo->verifyTicket = 'ticket@@@J-2aIcFxaHc0OEnuCEdcoTxbNF8Ref_6kcuuJr5FwkwEfRsBKzoTcncnSgs4V2bvHYEGw-hoNCmWNfaIQvSw5Q';
        $componentInfo->zeroUpdatedAt = time();
        $componentInfo->accessToken = 'YM9Dah9ZW2pFkzsA1q3RAOD5WtwuiZDpcDxjwW-iAc8mi3VZOXvearG2fq1Fsw-ctB_rne6EkZ_a4XNhv3_cK4bh_pi0HHJQ_TlsmRP8SagTAOdABABIW';
        $componentInfo->zeroExpiresIn = 7200;
        $componentInfo->oneUpdatedAt = time();
        $componentInfo->insert();
    }
}